table 'Measures Table'
	lineageTag: 9b405508-fe68-4d05-a847-fcc83dc9008d

	measure 'Sum of Sales' = SUM( EPOS[sell_out_amt] )
		displayFolder: /Aggs
		lineageTag: 0eadd384-411c-4305-a944-b5d73084137c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Max of Sales' = MAX( EPOS[sell_out_amt] )
		lineageTag: 0020ba62-d769-49af-97d4-a904293abd1a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Average of Sales' = AVERAGE( EPOS[sell_out_amt] )
		formatString: "£"#,0.00;-"£"#,0.00;"£"#,0.00
		lineageTag: dc6f81cc-3d2a-4f76-ad23-3064c2115a3e

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	partition 'Measures Table' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

